# Generated by Django 4.0.8 on 2023-04-10 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('foundation_class_choices', models.CharField(choices=[('C1', "Class one - 'put subject name here' "), ('C2', "Class two - 'put subject name here'"), ('C3', "Class three - 'put subject name here'"), ('C4', "Class four - 'put subject name here'"), ('C5', "Class five - 'put subject name here'"), ('C6', "Class six - 'put subject name here'"), ('C7', "Class seven - 'put subject name here'")], default='C1', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
