# Generated by Django 4.0.8 on 2023-01-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='owner',
        ),
    ]
