# Generated by Django 4.0.8 on 2023-01-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_rename_classid_snippet_courseid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classesAttended',
            field=models.IntegerField(),
        ),
    ]
