# Generated by Django 4.0.8 on 2023-03-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignmentTitle', models.TextField(blank=True, default='', max_length=100)),
                ('students', models.ManyToManyField(to='students.student')),
            ],
        ),
    ]
